### ISSUE TITLE
Change Top Nav Bar Coloring to Adhere to Material Design Guidelines, and Make Black Text Stand Out More

### ISSUE THREAD

**Issue by Sanrax** [flashcarts/wiki#2]
I propose changing the top nav bar color to #EF5350, taken from this Material Design colors web page: https://materialui.co/colors/red

Currently the top bar color feels very washed out, and dark enough it makes the black text blend into the dark red background. This color makes the text stand out more, and doesn't feel as washed out.

Color comparison below.

![Screenshot_20230727_104605](https://github.com/flashcarts/wiki/assets/61475057/4eb1e6f5-e175-4cad-a0fe-c265b2896c07)

**Comment by Deletecat** [comment]
I think it looks better with the new colour!

**Comment by Sanrax** [comment]
> I think it looks better with the new colour!

~~colour~~ color :)
