### ISSUE TITLE
Create a README containing a link to the website

### ISSUE THREAD

**Issue by Sanqui** [flashcarts/wiki#5]
If this is a launched project, I recommend adding a link to the website in the README of this repository.  I discovered this repository on GitHub and it's relevant to my interests, but I was only able to identify the website https://flashcarts.net/ after checking the screenshot on the other issue ;)

**Comment by Epicpkmn11** [comment]
The GitHub metadata should link to it too:
![image](https://github.com/flashcarts/wiki/assets/41608708/5e66137d-4824-4996-8036-9d3f3c01a8c9)
